### ISSUE TITLE
Your Oxygen module is not working properly.

### ISSUE THREAD

**Issue by Boolyman** [Meldexun/BetterDiving#24]
Oxygen is not working right in your mod.  I dont know what it is, but it is changing countdown speed sporadically.  With or without an oxygen tank it is very buggy and starts counting down very fast.  I had a streamer testing my new pack last night, and you can see him experiencing the issue at 7:24:00 in the VOD https://www.twitch.tv/videos/451599001  and he tests it a few more times around 7:28:20 and over the next few minutes.  

Here is the pastebin of my config file  https://pastebin.com/xPcR8qSp

**Comment by Meldexun** [comment]
Thank you for reporting the bug. It seems that the method for the airEfficiency is screwed up. But it will be fixed with the next update.
Just to be sure i'm not looking at the wrong code. His world is around 256 blocks filled with water. (That would mean at the height of 70 you are 180 blocks under water and 180 / 30 = 6. So the oxygen usage would be 7 times as high.)
The part were he didn't consumed energy he had the waterbreathing buff. So that is not bug.

PS: I started with the energy system for the seamoth (and other items that might come in the future)

**Comment by Boolyman** [comment]
Yes the ocean goes to build limit.  I have oxygen efficiency by depth turned off in the config because of this.  If the config ignores that, then that explains the issue.   Good to hear you are working on an update. Thanks for your hard work.

**Comment by Meldexun** [comment]
Fixed with v1.3.80.
