### ISSUE TITLE
More Better Diving Issues

### ISSUE THREAD

**Issue by Boolyman** [Meldexun/BetterDiving#40]
I love your mod, and it is integral to my new pack... but the constant issues with it are very troublesome.  
First, may I recommend that next time, you use full complete sentences here ...

_"entity registry name renames > Transform your seamoths into items"_

...to let people know "This update will delete any seamoths currently in world.  To avoid this you must pick up the seamoth as an item."  I didn't know that cryptic message meant such things, and now there are 10k people playing my pack that had their seamoths deleted.  At least thats better than them losing their Hardcore worlds due to an Oxygen bug.

Second... Swim speed increases from Fins don't work.  They provide little, if any, swim speed bonus despite my config stating they should apply 30, 50, 75 percent increases.

I am at your mercy here... it is too late, and your mod is too big of a part of my pack, for me to try to find a different option.  Your mod is unique, the seamoth is awesome, the scuba gear is (was) amazing.  I just really wish these things were managed a bit more cleanly.

Third... why do people now sink when they are in the water?  My config options are identical to how they were before the update... why has the swimming mechanic changed?

**These issues are for version 1.4.01
MC version 1.12.2
Foreg - 14.23.5.2847**

My configs.... https://pastebin.com/Kj8FX35T

**Comment by Meldexun** [comment]
1. The part that you should pick up your seamoths as an item i have to admit i could describe that better. I'm sorry.
2. As it says on the curseforge description (or the description of the swimSpeed in the config) there are swim speed bonus limits (min: 1/3 of base speed, max 4/3 of base speed). I could add option to disable/configure that.
3. You have enabled the vanillaDivingMovement option in the General category of the config.
I hope you still enjoy the mod.

PS: Some notes on your config options:
1. I would recommend to just disable the ore module instead of manually disabling the ores. Especially setting the generation amount to 0 isn't useful because there will still be done some calculations when generating new chunks.
2. Configuring the airEfficiencyLimit doesn't do anything when you disable the airEfficiency setting.
3. The bug which lead to desyncs of the client and the server was fixed. The oxygenSyncPackets option has nothing to do with that and i don't recommend to enable it by default (though you can of course).

**Comment by Boolyman** [comment]
Regardless of the limits, since my values are within those limits, there should be at least SOME difference when a player wears the fins, right?   Right now there is no difference... wearing Fins does nothing.  If my values are wrong, what values DO you want me to use if I want the player to go 30%, 50%, and 75% faster with each tier of fins?

Vanilla movement was "true" in my previous config and people didnt sink... something had to change, either in the meaning of the boolean, or elsewhere.

**Comment by Meldexun** [comment]
No, your values exceed the limits. I meant that you have your base swim speed and with the bonuses calculated the actual swim speed is between 1/3 and 4/3 of the base swim speed. (50% and 70% clearly exceed the limit).
And your old config was messed up. At some time you updated the mod but didn't delete the old config file. What i mean is looking at your config file from #37 every option exists twice.

**Comment by Boolyman** [comment]
Ok... well I guess I have no idea how to do the advanced calculus required to edit the new configs.  So ill just have to leave it at default unfortunately.

**Comment by Meldexun** [comment]
The config really doesn't require you to do advanced calculus. I mean i never really changed how the config options work. I mostly just changed names or in which category a setting is located in.

And for the swim speed limits this is the simple calculation:
lowerSwimSpeedLimit = baseSwimSpeed / 3
upperSwimSpeedLimit = baseSwimSpeed / 3 * 4

Also i can give you an example:
swimSpeed=0.04
standardFinsMovespeed=0.4
standardO2tankMovespeed=-0.1
swimSpeedWithBonuses=0.04 * (1.0 + 0.4 - 0.1)=0.052
lowerSwimSpeedLimit=0.04 / 3=0.013333
upperSwimSpeedLimit=0.04 / 3 * 4=0.053333
swimSpeedWithBonuses is between limits: 0.013333 < 0.052 < 0.053333
-> actualSwimSpeed=0.052

**Comment by Boolyman** [comment]
So its not possible to swim more than 33% faster than base swim speed? :-/

**Comment by Meldexun** [comment]
No, that is not possible (also not in older versions). Though as i said i can add an option to disable/configure the limits.
(If you don't have any further questions i ask you to close this issue. Otherwise i will close it in a few days when you didn't write/ask anything else)

**Comment by Meldexun** [comment]
Though you should note that you might not swim ~1.33 times faster with the bonus of the fins set to 33% because equipping an oxygen tank reduces your swim speed.
So when you have fins with 33% bonus and a tank with -10% penality you will swim with 1.23 times of the base swim speed.
For base speed of 0.04 (=> lowerLimit = 0.0133, upperLimit = 0.0533):
speed = base * (1 + bonuses - penalities) = 0.04 * (1 + 0.33 - 0.1) = 0.0492
So increasing the bonus there isn't useless:
Fins bonus speed of 50%:
speed = base * (1 + bonuses - penalities) = 0.04 * (1 + 0.50 - 0.1) = 0.056 => limited to 0.0533
