### ISSUE TITLE
Fluid type whitelist/blacklist for movement module

### ISSUE THREAD

**Issue by barttraeger** [Meldexun/BetterDiving#43]
**Enhancement**
Hi, love your mod, great work!
It would be nice to have a whitelist/blacklist in the config for movement behavior in different fluids.
E.g. swimming in lava would only work the vanilla way, so that you are automatically sinking.

Another thing: right now the quicksand from Biomes O Plenty doesn't drag you down with the movement module enabled, you sink one block and then "float" there.

Implementing a config for enabling/disabling the movement module in different fluids would
solve this and greatly improve overall compatibility.

**Comment by Meldexun** [comment]
Good idea but it's more complicated. I'm not checking if the player is inside a fluid. I'm using vanilla methods and iirc they check for the material.
And because the material of lava isn't water in lava everything works like in vanilla.
And because the material of quicksand is water the movement is changed.
So a black-/whitelist would require a custom check in which fluid the player currently is.

This is not a thing i'm currently planning to do. Because it's harder to implement than i looks like and i'm focusing mostly on features, game breaking issues and performance.

**Comment by barttraeger** [comment]
Oh, I see, thats too bad. Thank you anyways, it's a great mod!
