### ISSUE TITLE
velocity of "1.13-like movement"

### ISSUE THREAD

**Issue by Biviho** [Meldexun/BetterDiving#53]
hi, i wanted to ask if is possible to add a configurable velocity of the sinking movement using the 1.13-like option.
It would be great to have the ability to insert negative values so that you will be able to slowly float to add more realism.

**Comment by Meldexun** [comment]
Do you want a option where you define something like -0.01 so that the player slowly sinks (depending on the value)? Though i probably won't add that because that is one of the annoying things about minecraft water that you always just get pushed downwards.
Also there is a 1.13 like config option to change the movement to be similar to vanilla 1.13.
