### ISSUE TITLE
Other dimension generation.

### ISSUE THREAD

**Issue by disastercube** [Meldexun/BetterDiving#70]
I'm not sure if this is a bug or me being blind but I'm trying to make seagrass spawn in another dimension (twilight forest id 7 ) but it is not working. Is there something wrong with this code ?

#Biomes in which this plant/ore can generate. For Mod-Biomes: modid:biome_name. Definitely supported mods: BiomesOPlenty.
            S:biomes <
            twilight_stream
            twilight_lake
            >

#Dimensions in which this plant/ore can generate.
            I:dimensions <
                0
                7
             >

**Comment by disastercube** [comment]
I tried with all of this as well:
                twilight:twilight_stream
                twilight:twilight_lake
                7:twilight_stream
                7:twilight_lake
                twilight:stream
                twilight:Lake
                7:stream
                7:lake
                stream
                lake

**Comment by Meldexun** [comment]
So first of all there is a comment which explains how to add new biomes. It says "For Mod-Biomes: modid:biome_name". That would be twilightforest:twilight_stream and so on.
The problem is that the twilight forest isn't properly coded. What i mean is that when i want to get the sea level of the current world (world = dimension) then it isn't returning me the sea level of the twilight forest but the default sea level of 63. And so there won't spawn any plants in that dimension.
